// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMvOT7N2fYPRWV98-xiWOVAjIvWMy-Jis',
    appId: '1:1093187474465:android:162ab552d6ff1bd601ff60',
    messagingSenderId: '1093187474465',
    projectId: 'monitor-stress',
    databaseURL: 'https://monitor-stress-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'monitor-stress.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWdR1ZMSrwXHGlzAkHiq6OaW66kAq0-qo',
    appId: '1:1093187474465:ios:8a1a827beb2b779701ff60',
    messagingSenderId: '1093187474465',
    projectId: 'monitor-stress',
    databaseURL: 'https://monitor-stress-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'monitor-stress.appspot.com',
    iosBundleId: 'com.example.monitoringStress',
  );
}
